name: melody-transcription
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.3
  - numpy=1.24.3
  - scipy=1.11.4
  - librosa=0.10.1
  - pip:
      - music21==9.1.0
      - sounddevice==0.4.6
      - PySide6==6.6.1
      - pyinstaller==6.3.0
      - pytest==7.4.3
      - resampy==0.4.2
